FROM udung/ace:12.0.11.0

USER root

COPY ./bar/*.bar /tmp/
RUN export LICENSE=accept \
    && . /opt/ibm/ace-12/server/bin/mqsiprofile \
    && set -x && for FILE in /tmp/*.bar; do \
       echo "$FILE" >> /tmp/deploys && \
       ibmint package --compile-maps-and-schemas --input-bar-file "$FILE" --output-bar-file /tmp/temp.bar  2>&1 | tee -a /tmp/deploys && \
       ibmint deploy --input-bar-file /tmp/temp.bar --output-work-directory /home/aceuser/ace-server/ 2>&1 | tee -a /tmp/deploys; done \
    && ibmint optimize server --work-dir /home/aceuser/ace-server \
    && chmod -R ugo+rwx /home/aceuser/ \
    && chmod -R ugo+rwx /var/mqsi/ && mkdir -p /tmp/input && mkdir -p /tmp/output && chmod 777 -R /tmp/input && chmod 777 -R /tmp/output

USER 1000


ENTRYPOINT ["bash", "-c", ". /opt/ibm/ace-12/server/bin/mqsiprofile && mqsisetdbparms -n sftp::secid -u wmuser -p wmuser123 --work-dir /home/aceuser/ace-server && IntegrationServer --name ace-server -w /home/aceuser/ace-server  "]
